'use strict';

// v15.98.48 — INJ Node Command Center. Dedicated wide-screen monitor surface.
const $ = id => document.getElementById(id);
const HOUR = 60 * 60_000;
const DAY = 24 * HOUR;
const INJ_DECIMALS = 1e18;
const LCD_ENDPOINTS = ['https://sentry.lcd.injective.network:443','https://lcd.injective.network','https://1rpc.io/inj-lcd'];
const APR_ENDPOINT = 'https://api.ui.injective.network/api/v1/cache/stats/apr';
const privacy = localStorage.getItem('inj_monitor_privacy') === '1';
const currency = localStorage.getItem('inj_monitor_currency') === 'EUR' ? 'EUR' : 'USD';
const ranges = {
  m5:{ms:5*60_000,canvas:'ccCanvas5m',card:'.cc-chart-5m',ids:['cc5Top','cc5Mid','cc5Bottom','cc5Marker'],minSpan:.00007,max:260},
  m10:{ms:10*60_000,canvas:'ccCanvas10m',card:'.cc-chart-10m',ids:['cc10Top','cc10Mid','cc10Bottom','cc10Marker'],minSpan:.00010,max:260},
  h1:{ms:HOUR,canvas:'ccCanvas1h',card:'.cc-chart-1h',ids:['cc1hTop','cc1hMid','cc1hBottom','cc1hMarker'],minSpan:.00022,max:280},
  d1:{ms:DAY,canvas:'ccCanvas1d',card:'.cc-chart-1d',ids:['cc1dTop','cc1dMid','cc1dBottom','cc1dMarker'],minSpan:.0013,max:260},
  w1:{ms:7*DAY,canvas:'ccCanvas1w',card:'.cc-chart-1w',ids:['cc1wTop','cc1wMid','cc1wBottom','cc1wMarker'],minSpan:.0030,max:250}
};
const state = {
  address:'',walletLabel:'Wallet',available:0,staked:0,rewards:0,total:0,apr:0,networkApr:0,commission:0,validators:[],avgPrice:0,
  price:0,target:0,visual:0,open24:0,low24:0,high24:0,change24:0,eur:1,
  short:[],day:[],week:[],scales:{},ws:null,reconnect:0,raf:0,lastFrame:0,lastDraw:0,lastSync:0,apiOk:false,marketOk:false,stopped:false
};
Object.keys(ranges).forEach(k=>state.scales[k]=null);

const n=v=>Number.isFinite(Number(v))?Number(v):0;
const fromWei=v=>n(v)/INJ_DECIMALS;
const rate=v=>{const x=n(v);return x>1?x/INJ_DECIMALS:x};
const validAddress=v=>/^inj1[0-9a-z]{35,55}$/i.test(String(v||''));
const shortAddress=v=>v?`${v.slice(0,8)}…${v.slice(-6)}`:'—';
function fmtInj(v,d=4){return n(v).toLocaleString('it-IT',{minimumFractionDigits:d,maximumFractionDigits:d})+' INJ'}
function priceText(v){return v>0?'$'+v.toLocaleString('en-US',{minimumFractionDigits:v<10?4:3,maximumFractionDigits:v<10?4:3}):'—'}
function money(v,d=2){const x=n(v)*(currency==='EUR'?state.eur:1);return new Intl.NumberFormat('it-IT',{style:'currency',currency,minimumFractionDigits:d,maximumFractionDigits:d}).format(x)}
function pct(v,d=2){const x=n(v);return `${x>0?'+':''}${x.toFixed(d)}%`}
function setText(id,text){const el=$(id);if(el&&el.textContent!==text)el.textContent=text}
function setDot(id,mode){const el=$(id);if(!el)return;el.classList.toggle('ok',mode==='ok');el.classList.toggle('bad',mode==='bad')}
function applyPrivacy(){if(!privacy)return;document.querySelectorAll('.private').forEach(el=>el.classList.add('privacy-on'))}
async function fetchJson(url,timeout=8000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{cache:'no-store',signal:c.signal});if(!r.ok)throw new Error(String(r.status));return await r.json()}finally{clearTimeout(t)}}
async function lcd(path){let err;for(const base of LCD_ENDPOINTS){try{const data=await fetchJson(base+path,7500);state.apiOk=true;return data}catch(e){err=e}}state.apiOk=false;throw err||new Error('lcd')}
function findInj(coins=[]){const c=coins.find(x=>x?.denom==='inj');return c?fromWei(c.amount):0}
function rewardTotal(data){return (data?.total||[]).filter(x=>x?.denom==='inj').reduce((s,x)=>s+fromWei(x.amount),0)}
function delegationRows(data){return (data?.delegation_responses||[]).map(r=>({operator:r?.delegation?.validator_address||'',amount:fromWei(r?.balance?.amount)})).filter(r=>r.operator&&r.amount>0)}
function loadLocal(){
  try{const wallets=JSON.parse(localStorage.getItem('inj_monitor_wallets_v1')||'[]');state.address=(localStorage.getItem('inj_monitor_address')||'').toLowerCase();const w=Array.isArray(wallets)?wallets.find(x=>x.address===state.address):null;if(w?.label)state.walletLabel=w.label}catch(_){}
  try{const s=JSON.parse(localStorage.getItem('inj_monitor_summaries_v1')||'{}')[state.address]||{};state.available=n(s.available);state.staked=n(s.staked);state.rewards=n(s.rewards);state.total=n(s.total)||(state.available+state.staked+state.rewards);state.apr=n(s.personalApr);state.networkApr=n(s.networkApr);state.commission=n(s.weightedCommission);state.validators=Array.isArray(s.validators)?s.validators:[];state.lastSync=n(s.updated)}catch(_){}
  try{const a=JSON.parse(localStorage.getItem('inj_monitor_average_buy_price_v1')||'{}');state.avgPrice=n(a[state.address])}catch(_){}
}
async function loadFx(){if(currency!=='EUR')return;try{const d=await fetchJson('https://api.frankfurter.app/latest?from=USD&to=EUR',5000);if(n(d?.rates?.EUR)>0)state.eur=n(d.rates.EUR)}catch(_){}}
async function refreshWallet(){if(!validAddress(state.address)){renderWallet();return}setText('ccWalletState','SYNC');setDot('ccDataDot','');try{
  const [bank,deleg,reward,aprRaw]=await Promise.all([lcd(`/cosmos/bank/v1beta1/balances/${state.address}`),lcd(`/cosmos/staking/v1beta1/delegations/${state.address}`),lcd(`/cosmos/distribution/v1beta1/delegators/${state.address}/rewards`),fetchJson(APR_ENDPOINT,6500).catch(()=>null)]);
  state.available=findInj(bank?.balances||[]);const rows=delegationRows(deleg);state.staked=rows.reduce((s,r)=>s+r.amount,0);state.rewards=rewardTotal(reward);state.total=state.available+state.staked+state.rewards;const official=n(aprRaw?.apr);state.networkApr=official>0?(official<1?official*100:official):state.networkApr;
  const validators=await Promise.all(rows.slice(0,8).map(async row=>{try{const d=await lcd(`/cosmos/staking/v1beta1/validators/${row.operator}`);const v=d?.validator||{};return {...row,moniker:v?.description?.moniker||shortAddress(row.operator),commission:Math.max(0,Math.min(1,rate(v?.commission?.commission_rates?.rate))),status:v?.status||'',jailed:Boolean(v?.jailed)}}catch(_){return {...row,moniker:shortAddress(row.operator),commission:0,status:'',jailed:false}}}));
  state.validators=validators;const delegated=validators.reduce((s,r)=>s+r.amount,0);state.commission=delegated>0?validators.reduce((s,r)=>s+r.amount*n(r.commission),0)/delegated:0;const annual=validators.reduce((s,r)=>s+r.amount*state.networkApr*Math.max(0,1-n(r.commission))/100,0);state.apr=state.staked>0?annual/state.staked*100:state.apr;state.lastSync=Date.now();state.apiOk=true;setText('ccWalletState','ONLINE');setDot('ccDataDot','ok');setText('ccApiState','ONLINE');setDot('ccApiDot','ok');
  try{const all=JSON.parse(localStorage.getItem('inj_monitor_summaries_v1')||'{}');all[state.address]={...(all[state.address]||{}),available:state.available,staked:state.staked,rewards:state.rewards,total:state.total,personalApr:state.apr,networkApr:state.networkApr,weightedCommission:state.commission,validators:state.validators,updated:state.lastSync};localStorage.setItem('inj_monitor_summaries_v1',JSON.stringify(all))}catch(_){}
}catch(_){setText('ccWalletState','CACHE');setDot('ccDataDot','bad');setText('ccApiState','RETRY');setDot('ccApiDot','bad')}renderWallet();renderValidators();renderSystem()}
async function fetchKlines(interval,limit){const d=await fetchJson(`https://api.binance.com/api/v3/klines?symbol=INJUSDT&interval=${interval}&limit=${limit}`,8000);const now=Date.now();return d.map(r=>({t:Math.min(n(r[6])||n(r[0]),now),p:n(r[4])})).filter(r=>r.p>0)}
async function loadMarketHistory(){try{const [short,day,week,ticker]=await Promise.all([fetchKlines('1m',61),fetchKlines('5m',289),fetchKlines('30m',337),fetchJson('https://api.binance.com/api/v3/ticker/24hr?symbol=INJUSDT',7000)]);state.short=short;state.day=day;state.week=week;state.price=n(ticker?.lastPrice)||short.at(-1)?.p||0;state.target=state.price;state.visual=state.price;state.open24=n(ticker?.openPrice);state.low24=n(ticker?.lowPrice);state.high24=n(ticker?.highPrice);state.change24=n(ticker?.priceChangePercent);state.marketOk=true;renderAll()}catch(_){state.marketOk=false;renderSystem()}}
function addTick(p,t=Date.now()){if(!(p>0))return;state.price=p;state.target=p;const last=state.short.at(-1);if(last&&t-last.t<800){last.t=t;last.p=p}else state.short.push({t,p});const cutoff=t-HOUR-120000;while(state.short.length>2&&state.short[0].t<cutoff)state.short.shift();if(state.day.length){const d=state.day.at(-1);if(t-d.t<5*60_000){d.t=t;d.p=p}else state.day.push({t,p})}if(state.week.length){const w=state.week.at(-1);if(t-w.t<30*60_000){w.t=t;w.p=p}else state.week.push({t,p})}}
function connectMarket(){if(state.stopped||document.hidden)return;clearTimeout(state.reconnect);try{const ws=new WebSocket('wss://stream.binance.com:9443/ws/injusdt@miniTicker');state.ws=ws;ws.onopen=()=>{state.marketOk=true;setText('ccMarketState','ONLINE');setDot('ccMarketDot','ok');$('ccConnection')?.classList.remove('offline')};ws.onmessage=e=>{try{const d=JSON.parse(e.data),p=n(d.c);if(p>0){addTick(p);state.open24=n(d.o)||state.open24;state.high24=n(d.h)||state.high24;state.low24=n(d.l)||state.low24;state.change24=state.open24>0?(p/state.open24-1)*100:state.change24;renderFast()}}catch(_){}};ws.onclose=()=>{if(state.ws===ws)state.ws=null;state.marketOk=false;setText('ccMarketState','RECONNECT');setDot('ccMarketDot','bad');state.reconnect=setTimeout(connectMarket,1800)};ws.onerror=()=>{}}catch(_){state.marketOk=false;state.reconnect=setTimeout(connectMarket,2200)}}
function chartSource(key){return key==='d1'?state.day:key==='w1'?state.week:state.short}
function firstAtOrBefore(arr,start){let idx=0;for(let i=0;i<arr.length;i++){if(arr[i].t<=start)idx=i;else break}return idx}
function sampleShape(rows,max){if(rows.length<=max)return rows;const out=[rows[0]],buckets=Math.max(1,Math.floor((max-2)/4)),size=Math.ceil(rows.length/buckets);for(let s=0;s<rows.length;s+=size){const e=Math.min(rows.length-1,s+size-1);let lo=s,hi=s;for(let i=s+1;i<=e;i++){if(rows[i].p<rows[lo].p)lo=i;if(rows[i].p>rows[hi].p)hi=i}const ids=[s,lo,hi,e].filter((x,i,a)=>a.indexOf(x)===i).sort((a,b)=>a-b);ids.forEach(i=>{const r=rows[i];if(out.at(-1)?.t!==r.t)out.push(r)})}if(out.at(-1)?.t!==rows.at(-1).t)out.push(rows.at(-1));return out.slice(0,max-1).concat(out.at(-1))}
function chartColor(card,dir){card.classList.remove('up','down','neutral');card.classList.add(dir>0?'up':dir<0?'down':'neutral');const cs=getComputedStyle(document.documentElement);return cs.getPropertyValue(dir>0?'--up':dir<0?'--down':'--accent').trim()}
function hexAlpha(hex,a){const h=String(hex||'').trim();if(/^#[0-9a-f]{6}$/i.test(h)){const r=parseInt(h.slice(1,3),16),g=parseInt(h.slice(3,5),16),b=parseInt(h.slice(5,7),16);return `rgba(${r},${g},${b},${a})`}return h}
function resizeCanvas(c){const r=c.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,1.65),w=Math.max(2,Math.round(r.width*dpr)),h=Math.max(2,Math.round(r.height*dpr));if(c.width!==w||c.height!==h){c.width=w;c.height=h;c._dpr=dpr}return {w:r.width,h:r.height,dpr}}
function drawChart(key,now,dt){const cfg=ranges[key],c=$(cfg.canvas),card=document.querySelector(cfg.card);if(!c||!card||!(state.visual>0))return;const src=chartSource(key),start=now-cfg.ms;let i=firstAtOrBefore(src,start),rows=src.slice(i).filter(r=>r.t<=now&&r.p>0);if(!rows.length)rows=[{t:start,p:state.visual}];if(rows[0].t>start)rows.unshift({t:start,p:rows[0].p});rows.push({t:now,p:state.visual});rows=sampleShape(rows,cfg.max);let min=Math.min(...rows.map(r=>r.p)),max=Math.max(...rows.map(r=>r.p));const floor=Math.max(state.visual*cfg.minSpan,state.visual<10?.00005:.0005);let span=max-min;if(span<floor){const mid=(max+min)/2;min=mid-floor/2;max=mid+floor/2;span=floor}const tmin=min-span*.12,tmax=max+span*.12;let sc=state.scales[key];if(!sc)sc=state.scales[key]={min:tmin,max:tmax};else{const aE=1-Math.exp(-dt/180),aR=1-Math.exp(-dt/3800);sc.min+=(tmin-sc.min)*(tmin<sc.min?aE:aR);sc.max+=(tmax-sc.max)*(tmax>sc.max?aE:aR)}min=sc.min;max=sc.max;span=Math.max(max-min,floor);const {w,h,dpr}=resizeCanvas(c),ctx=c.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);const left=8,right=w-7,top=7,bottom=h-8,ph=bottom-top,pw=right-left;const points=rows.map(r=>({x:left+Math.max(0,Math.min(1,(r.t-start)/cfg.ms))*pw,y:bottom-Math.max(0,Math.min(1,(r.p-min)/span))*ph,p:r.p}));const firstPrice=rows[0].p,dir=Math.abs(state.visual-firstPrice)<Math.max(state.visual*.000012,.000002)?0:Math.sign(state.visual-firstPrice),color=chartColor(card,dir);ctx.lineWidth=1;ctx.strokeStyle='rgba(135,165,205,.055)';[.25,.5,.75].forEach(f=>{const y=top+ph*f;ctx.beginPath();ctx.moveTo(left,y);ctx.lineTo(right,y);ctx.stroke()});ctx.strokeStyle='rgba(135,165,205,.028)';[1/3,2/3].forEach(f=>{const x=left+pw*f;ctx.beginPath();ctx.moveTo(x,top);ctx.lineTo(x,bottom);ctx.stroke()});if(points.length>1){ctx.beginPath();ctx.moveTo(points[0].x,points[0].y);for(let k=1;k<points.length;k++)ctx.lineTo(points[k].x,points[k].y);ctx.lineWidth=3.2;ctx.lineJoin='round';ctx.lineCap='round';ctx.strokeStyle=hexAlpha(color,.09);ctx.stroke();ctx.beginPath();ctx.moveTo(points[0].x,points[0].y);for(let k=1;k<points.length;k++)ctx.lineTo(points[k].x,points[k].y);ctx.lineWidth=1.15;ctx.strokeStyle=hexAlpha(color,.92);ctx.stroke();const last=points.at(-1),pulse=.5+.5*Math.sin(now/420);ctx.beginPath();ctx.arc(last.x,last.y,6.4+pulse*1.2,0,Math.PI*2);ctx.fillStyle=hexAlpha(color,.09+pulse*.03);ctx.fill();ctx.beginPath();ctx.arc(last.x,last.y,3.25,0,Math.PI*2);ctx.fillStyle=color;ctx.fill();ctx.lineWidth=1.5;ctx.strokeStyle=getComputedStyle(document.documentElement).getPropertyValue('--canvas').trim();ctx.stroke();setText(cfg.ids[0],priceText(max));setText(cfg.ids[1],priceText((min+max)/2));setText(cfg.ids[2],priceText(min));const marker=$(cfg.ids[3]);if(marker){marker.textContent=priceText(state.visual);marker.style.top=Math.max(8,Math.min(92,100-(state.visual-min)/span*100))+'%'}}}
function renderWallet(){setText('ccWalletName',state.walletLabel);setText('ccWalletAddress',shortAddress(state.address));setText('ccNetWorth',state.price>0?money(state.total*state.price):'—');setText('ccTotalInj',fmtInj(state.total,4));setText('ccAvailable',fmtInj(state.available,4));setText('ccStaked',fmtInj(state.staked,4));setText('ccRewards',fmtInj(state.rewards,4));setText('ccAvgPrice',state.avgPrice>0?money(state.avgPrice):'—');const pnl=state.avgPrice>0&&state.price>0?(state.price-state.avgPrice)*state.total:0,pnlPct=state.avgPrice>0?(state.price/state.avgPrice-1)*100:0;setText('ccTotalPnl',state.avgPrice>0?money(pnl):'—');setText('ccTotalPnlPct',state.avgPrice>0?pct(pnlPct):'—');setText('ccApr',state.apr>0?state.apr.toFixed(3)+'%':'—');setText('ccNetworkApr',state.networkApr>0?state.networkApr.toFixed(3)+'%':'—');setText('ccCommission',state.commission>0?(state.commission*100).toFixed(2)+'%':'—');const daily=state.staked>0&&state.apr>0?state.staked*state.apr/100/365:0;setText('ccDailyReward',daily>0?fmtInj(daily,6):'—');setText('ccDailyRewardUsd',daily>0&&state.price>0?money(daily*state.price):'—');setText('ccPulseRewardValue',daily>0?fmtInj(daily,6):'—');setText('ccPulseRewardUsd',daily>0&&state.price>0?money(daily*state.price):'—');setText('ccStakeRatio',state.total>0?(state.staked/state.total*100).toFixed(1)+'%':'—');setText('ccValidatorCount',`${state.validators.length||0} validator${state.validators.length===1?'':'s'}`);setText('ccFooterApr',state.apr>0?state.apr.toFixed(3)+'%':'—');setText('ccFooterReward',daily>0?daily.toFixed(6)+' INJ':'—');applyPrivacy()}
function renderValidators(){const host=$('ccValidatorList');if(!host)return;host.replaceChildren();if(!state.validators.length){const e=document.createElement('span');e.className='cc-empty';e.textContent='Nessuna delega rilevata';host.append(e);return}state.validators.slice(0,3).forEach(v=>{const row=document.createElement('div');row.className='cc-validator-row';const name=document.createElement('strong');name.textContent=v.moniker||shortAddress(v.operator);const meta=document.createElement('span');meta.textContent=`${fmtInj(v.amount,2)} · fee ${(n(v.commission)*100).toFixed(2)}%`;const status=document.createElement('b');status.textContent=v.jailed?'JAILED':(v.status&&v.status!=='BOND_STATUS_BONDED'?'CHECK':'ACTIVE');if(v.jailed)status.style.color='var(--down)';row.append(name,meta,status);host.append(row)})}
function renderMarket(){setText('ccLivePrice',priceText(state.visual||state.price));setText('ccChange24',state.price>0?`${pct(state.change24)} · 24H`:'— · 24H');setText('ccLow24',priceText(state.low24));setText('ccHigh24',priceText(state.high24));setText('ccFooterLow',priceText(state.low24));setText('ccFooterHigh',priceText(state.high24));setText('ccSnapshot24',state.price>0?pct(state.change24):'—');const span=state.high24-state.low24,pos=span>0?Math.max(0,Math.min(100,(state.visual-state.low24)/span*100)):50;['ccRangeFill','ccFooterFill'].forEach(id=>{const e=$(id);if(e)e.style.width=pos+'%'});['ccRangeDot','ccFooterDot'].forEach(id=>{const e=$(id);if(e)e.style.left=pos+'%'});setText('ccRangePosition',pos.toFixed(1)+'%');const oneHourStart=state.short.find(r=>r.t>=Date.now()-HOUR)?.p||state.short[0]?.p||state.visual;const h1=oneHourStart>0?(state.visual/oneHourStart-1)*100:0;setText('ccMomentum',pct(h1));setText('ccSnapshot1h',pct(h1));const pEl=$('ccPulsePrice');pEl?.classList.remove('up','down','neutral');pEl?.classList.add(h1>0?'up':h1<0?'down':'neutral');const dailyPnl=state.open24>0?(state.visual-state.open24)*state.total:0,dailyPct=state.open24>0?(state.visual/state.open24-1)*100:0;setText('ccDailyPnl',state.open24>0?money(dailyPnl):'—');setText('ccDailyPnlPct',state.open24>0?pct(dailyPct):'—');const dEl=$('ccPulsePnl');dEl?.classList.remove('up','down','neutral','positive','negative');dEl?.classList.add(dailyPct>0?'positive':dailyPct<0?'negative':'neutral');renderWallet()}
function renderSystem(){setText('ccMarketState',state.marketOk?'ONLINE':'RECONNECT');setDot('ccMarketDot',state.marketOk?'ok':'bad');setText('ccApiState',state.apiOk?'ONLINE':'RETRY');setDot('ccApiDot',state.apiOk?'ok':'bad');setText('ccLastSync',state.lastSync?new Date(state.lastSync).toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit',second:'2-digit'}):'—');const ok=state.marketOk&&state.apiOk;setText('ccSystemOverall',ok?'OK':'CHECK');setText('ccFooterSystem',`SYSTEM · ${ok?'OK':'CHECK'}`);setText('ccFooterLive',state.marketOk?'LIVE':'RECONNECT');const conn=$('ccConnection');if(conn){conn.classList.toggle('offline',!state.marketOk)}}
function renderFast(){renderMarket();renderSystem()}
function renderAll(){renderWallet();renderValidators();renderMarket();renderSystem()}
function frame(ts){state.raf=0;if(state.stopped||document.hidden)return;const dt=Math.max(8,Math.min(120,ts-(state.lastFrame||ts-50)));state.lastFrame=ts;if(state.target>0){if(!(state.visual>0))state.visual=state.target;const delta=state.target-state.visual;state.visual+=delta*(1-Math.exp(-dt/125));if(Math.abs(delta)<.0000005)state.visual=state.target}if(ts-state.lastDraw>80&&state.visual>0){state.lastDraw=ts;const now=Date.now();Object.keys(ranges).forEach(k=>drawChart(k,now,dt));renderMarket()}state.raf=requestAnimationFrame(frame)}
function start(){if(!state.raf&&!document.hidden&&!state.stopped)state.raf=requestAnimationFrame(frame)}
function stop(){state.stopped=true;if(state.raf)cancelAnimationFrame(state.raf);clearTimeout(state.reconnect);try{state.ws?.close()}catch(_){}state.ws=null}
function clock(){setText('ccClock',new Date().toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit',second:'2-digit'}))}
$('ccBack')?.addEventListener('click',()=>{stop();if(history.length>1)history.back();else location.href='./index.html'});
document.addEventListener('visibilitychange',()=>{if(document.hidden){if(state.raf)cancelAnimationFrame(state.raf);state.raf=0;try{state.ws?.close()}catch(_){}}else if(!state.stopped){start();connectMarket()}});
window.addEventListener('resize',()=>Object.values(ranges).forEach(cfg=>{const c=$(cfg.canvas);if(c){c.width=0;c.height=0}}),{passive:true});
loadLocal();applyPrivacy();renderAll();clock();setInterval(clock,1000);setInterval(()=>{if(!document.hidden)refreshWallet()},60000);Promise.allSettled([loadFx(),loadMarketHistory()]).then(()=>{renderAll();start();connectMarket()});refreshWallet();
